FROM --platform=$BUILDPLATFORM python:3.12.5-bookworm AS development
ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG no_mqttmanager_build
WORKDIR /MQTTManager
SHELL ["/bin/bash", "-c"]

VOLUME /MQTTManager
VOLUME /web
# Update container
RUN apt-get update && apt-get -y upgrade && apt-get install -y nginx --no-install-recommends cmake build-essential gdb \
 curl npm postgresql-client curl inotify-tools net-tools sqlite3 vim build-essential protobuf-c-compiler cmake build-essential curl \
 && pip install -U conan conan-check-updates

RUN conan profile detect --force && echo 'core.cache:storage_path=/MQTTManager/conan_cache/' > ~/.conan2/global.conf \
&& sed -i "s|cppstd=gnu17|cppstd=gnu23|g" /root/.conan2/profiles/default \
&& sed -i "s|build_type=Release|build_type=Debug|g" /root/.conan2/profiles/default \
&& echo "alias ll='ls -lh --color=auto'" >> /etc/bash.bashrc

#RUN pip install --no-cache-dir -r requirements.txt
#RUN if [ -z "$no_mqttmanager_build" ]; then /bin/bash /MQTTManager/compile_mqttmanager.sh --target-platform "$TARGETPLATFORM"; else echo "Not building MQTTManager."; fi
# DON NOT RUN COMMANDS IN /MQTTManager OR IN /web both are not mounted during build

COPY nginx/sites-enabled/ /etc/nginx/sites-enabled/
COPY nginx/sites-templates/ /etc/nginx/sites-templates/
COPY "HMI_files/" /web/nspanelmanager/HMI_files/
RUN ln -sf /web /usr/src/app

EXPOSE 8000
CMD ["/bin/bash", "./run_uwsgi.sh"]

FROM --platform=$BUILDPLATFORM python:3.12.5-bookworm AS production
WORKDIR /web
SHELL ["/bin/bash", "-c"]
# Update container
RUN apt-get update && apt-get -y upgrade && apt-get install -y nginx

COPY web/ /web
COPY MQTTManager/build /MQTTManager/build
COPY nginx/sites-enabled/ /etc/nginx/sites-enabled/
COPY nginx/sites-templates/ /etc/nginx/sites-templates/
COPY "HMI_files/" /web/nspanelmanager/HMI_files/
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000
CMD ["/bin/bash", "./run_uwsgi.sh"]
